### PR TITLE
Add a possibility to set global classes without prefix.

### PR DESCRIPTION
**Pull request by lacedon**
I added new parameter **global_classes_prefix** to settings. If this parameter contain some string then all classes that have that string at the beginning will be added without prefix and this string.

### CODE REVIEW

**Comment by kizu** [comment]
I'm not sure this should be fixed this way. Right now I'm thinking of reverting the previous behaviour for all classes after the first, as there are a lot of issues (not only with prefix). I'll see if it could be done as a minor version, or as a major fix.

**Comment by lacedon** [comment]
I think it could be useful if prefix's added to not only first class.

On our project we've never had two block class for one tag
```jade
+b.block-1.block-2
<div class="b-block-1 b-block-2"></div>
```
But we use a possibility to add element class and block class for one tag
```jade
+b.global-block
	+b.__item.local-block
<div class="b-global-block">
	<div class="b-global-block__item b-local-block">
</div>
```
Do I understand right if it would parse to:
```jade
<div class="b-global-block">
	<div class="b-global-block__item local-block">
</div>
```
Maybe we can add some flag if add or not prefix?

**Comment by kizu** [comment]
I'm thinking of using the postfix element context syntax to mark up the blocks that need to have prefix (those that should be treated just as simple classes), so

``` Jade
+b.block-1.block-2
```

would be equal to

``` Jade
.b-block-1.block-2
```

while

``` Jade
+b.block-1.block-2__
```

would be equal to

``` Jade
.b-block-1.b-block-2
```

However, that would also mean that the nested items would inherit the second block in that case, which is not something that would be always wanted I guess :)

I'm trying to think of any other way to differentiate simple classes from BEM classes only using the syntax available for classnames, but can't find anything good atm.

**Comment by kizu** [comment]
In bemto.pug@2.1.0 I've added a way to setup the prefixes using an object, with it you can add a `global-` prefix (or any other name for it), so you could have those classnames without prefix at all. See [this part of Readme](https://github.com/kizu/bemto#objects-for-prefix-setting) on how to use this.

**Pull request closed without merging**
